#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/edward/bin/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/edward/code/BangumiN/app"
export "FLUTTER_TARGET=/Users/edward/code/BangumiN/app/lib/config/development.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/edward/bin/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.5.3"
export "FLUTTER_BUILD_NUMBER=17"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
