// credit to https://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application
import fs = require('fs');
import {combineLatest, Observable} from 'rxjs';

let exec = require('child_process').exec;

const revisionObservable = new Observable<string>(s => {
  exec('git rev-parse --short HEAD',
    function (error: Error, stdout: Buffer, stderr: Buffer) {
      if (error !== null) {
        console.log('git error: ' + error + stderr);
      }
      s.next(stdout.toString().trim());
      s.complete();
    });
});

const branchObservable = new Observable<string>(s => {
  exec('git rev-parse --abbrev-ref HEAD',
    function (error: Error, stdout: Buffer, stderr: Buffer) {
      if (error !== null) {
        console.log('git error: ' + error + stderr);
      }
      s.next(stdout.toString().trim());
      s.complete();
    });
});

combineLatest(revisionObservable, branchObservable)
  .subscribe(([revision, branch]) => {
    console.log(`version: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}'`);

    const content = '// this file is automatically generated by git.version.ts script\n' +
      `export const BuildVersion = {version: '${process.env.npm_package_version}', revision: '${revision}', branch: '${branch}'};\n`;

    fs.writeFileSync(
      __dirname + '/../src/environments/build-version.ts',
      content,
      {encoding: 'utf8'}
    );
  });
