/// Flutter icons MuninIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MuninIcons
///      fonts:
///       - asset: fonts/icons/MuninIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MuninIcons
///      fonts:
///       - asset: fonts/icons/MuninIcons.ttf
///
///
///

/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MuninIcons
///      fonts:
///       - asset: fonts/icons/MuninIcons.ttf
///
///
///

class MuninIcons {
  MuninIcons._();

  static const _kFontFam = 'MuninIcons';

  /// [muninCupertinoShare] is provided by @puranzhang
  static const IconData muninCupertinoShare =
      const IconData(0xe800, fontFamily: _kFontFam);

  /// [muninReplyCount] is from
  /// https://material.io/tools/icons/?icon=subdirectory_arrow_right&style=round
  static const IconData muninReplyCount =
      const IconData(0xe801, fontFamily: _kFontFam);

  static const IconData muninRoundedTriangle =
      const IconData(0xe802, fontFamily: _kFontFam);

  /// A old version of chat bubble in `cupertino_icons` package(0.1.3)
  static const IconData muninCupertinoChatBubble =
      const IconData(0xe803, fontFamily: _kFontFam);
}
