import 'package:flutter/material.dart';

/// Customized colors are generated by
/// https://material.io/design/color/#tools-for-picking-colors

const _bangumiPinkPrimaryValue = 0xFFF09199;

const MaterialColor bangumiPink = const MaterialColor(
  _bangumiPinkPrimaryValue,
  const <int, Color>{
    50: const Color(0xFFFFE9EE),
    100: const Color(0xFFFFC8D2),
    200: const Color(0xFFF09199),
    300: const Color(0xFFE56572),
    400: const Color(0xFFEE3D50),
    500: const Color(0xFFF32037),
    600: const Color(0xFFE41036),
    700: const Color(0xFFD20030),
    800: const Color(0xFFC50029),
    900: const Color(0xFFB6001D),
  },
);

/// Natori pink, primary color is taken from twitter banner
/// We might need to tweak this value since it's not accessibility compatible
const _natoriPinkPrimaryValue = 0XFFF7A4B9;
const MaterialColor natoriPink = const MaterialColor(
  _natoriPinkPrimaryValue,
  const <int, Color>{
    50: const Color(0XFFFCE9EE),
    100: const Color(0XFFFAC7D4),
    200: const Color(_natoriPinkPrimaryValue),
    300: const Color(0XFFF7819D),
    400: const Color(0XFFF76987),
    500: const Color(0XFFF85873),
    600: const Color(0XFFE65370),
    700: const Color(0XFFCF4C6A),
    800: const Color(0XFFBA4665),
    900: const Color(0XFF953B5C),
  },
);

/// Brown in natori's hair that's closest to 4.5:1 contrast ratio
const _natoriBrownPrimaryValue = 0xFF926F5C;
const MaterialColor natoriBrown = const MaterialColor(
  _natoriBrownPrimaryValue,
  const <int, Color>{
    50: const Color(0XFFF6EAE2),
    100: const Color(0XFFDECBC1),
    200: const Color(0XFFC3AA9D),
    300: const Color(0XFFA78978),
    400: const Color(_natoriBrownPrimaryValue),
    500: const Color(0XFF7D5641),
    600: const Color(0XFF714D3A),
    700: const Color(0XFF624131),
    800: const Color(0XFF533428),
    900: const Color(0XFF43271E),
  },
);

/// Brown in ion's hair that's closest to 4.5:1 contrast ratio
const _ionBrownPrimaryValue = 0XFF9C6D3A;
const MaterialColor ionBrown = const MaterialColor(
  _ionBrownPrimaryValue,
  const <int, Color>{
    50: const Color(0XFFFFE7BE),
    100: const Color(0XFFF1C79F),
    200: const Color(0XFFD4A67C),
    300: const Color(0XFFB38657),
    400: const Color(_ionBrownPrimaryValue),
    500: const Color(0XFF84551D),
    600: const Color(0XFF794B17),
    700: const Color(0XFF6A3E0F),
    800: const Color(0XFF5D3008),
    900: const Color(0XFF4E2200),
  },
);

/// Blue in ion's eye that's closest to 4.5:1 contrast ratio
const _ionBluePrimaryValue = 0XFF3A7DA6;
const MaterialColor ionBlue = const MaterialColor(
  _ionBluePrimaryValue,
  const <int, Color>{
    50: const Color(0XFFE3F6FA),
    100: const Color(0XFFBAE7F3),
    200: const Color(0XFF90D7EC),
    300: const Color(0XFF6EC6E4),
    400: const Color(0XFF5BBAE0),
    500: const Color(0XFF4FAEDB),
    600: const Color(0XFF48A0CD),
    700: const Color(0XFF3F8EBA),
    800: const Color(_ionBluePrimaryValue),
    900: const Color(0XFF2F5D83),
  },
);
